name: gp_rl_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3
  - pip
  - numpy=1.19.2
  - pytorch=1.7.0
  - cpuonly=1.0
  - threadpoolctl=2.1.0
  - matplotlib=3.3.2
  - scikit-learn=0.23.2
  - ffmpeg=4.2.2
  - pip:
    - gym==0.17.3
    - gpytorch==1.1.1
