name: gp_rl_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pytorch=2.0.0
  - cpuonly
  - matplotlib=3.6
  - scikit-learn=1.2.2
  - imageio=2.26.0
  - ffmpeg
  - pip:
    - gym==0.17.3
    - gpytorch
    - imageio[ffmpeg]
